WS\UserBundle\Entity\User:
    type: mappedSuperclass
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastName:
            type: string
            length: 140
            column: last_name
            nullable: true
        firstName:
            type: string
            length: 140
            column: first_name
            nullable: true
        ip:
            type: string
            length: 40
            column: ip
            nullable: true
        registerAt:
            type: datetime
            column: register_at
        birthAt:
            type: datetime
            column: birth_at
            nullable: true
