parameters:
    ws_user.form.user_factory.class: WS\UserBundle\Form\Factory\UserFactory
    ws_user.form.type.gender.class: WS\UserBundle\Form\Type\GenderType

services:
    ws_user.form.user_factory:
        class: '%ws_user.form.user_factory.class%'
        arguments:
            - '@form.factory'
            - '@router'
            - '%fos_user.model.user.class%'
            - '%ws_user.user.new.form%'
            - '%ws_user.user.edit.form%'

    ws_user.form.type.gender:
        class: '%ws_user.form.type.gender.class%'
        tags:
            - { name: form.type, alias: ws_gender }
