parameters:

services:
    ws_user.ip_listener:
        class: WS\UserBundle\EventListener\IpListener
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: kernel.event_subscriber }