WS\UserBundle\Entity\User:
    properties:
        lastName:
            - Length:
                min: 4
                max: 140
                minMessage: ws_user.user.lastName.length.min
                maxMessage: ws_user.user.lastName.length.max
                groups: [ Profile, Registration ]
        firstName:
            - Length:
                min: 4
                max: 140
                minMessage: ws_user.user.firstName.length.min
                maxMessage: ws_user.user.firstName.length.max
                groups: [ Profile, Registration ]
        birthAt:
            - Date:
                message: ws_user.user.birthAt.date.message
                groups: [ Profile, Registration ]
        gender:
            - Choice:
                choices:  [m, f, o]
                message:  ws_user.user.gender.choice.message
