ws_user_bundle_user_list:
    pattern:  /
    defaults: { _controller: "WSUserBundle:AdminUser:index" }

ws_user_bundle_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "WSUserBundle:AdminUser:show" }

ws_user_bundle_user_new:
    pattern:  /new
    defaults: { _controller: "WSUserBundle:AdminUser:new" }

ws_user_bundle_user_create:
    pattern:  /create
    defaults: { _controller: "WSUserBundle:AdminUser:create" }
    requirements: { _method: post }

ws_user_bundle_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "WSUserBundle:AdminUser:edit" }

ws_user_bundle_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "WSUserBundle:AdminUser:update" }
    requirements: { _method: post|put }

ws_user_bundle_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "WSUserBundle:AdminUser:delete" }
