WSUserBundle_password_ask:
    pattern:   '%ws_user.password_reset.path_ask%'
    defaults:  { _controller: 'WSUserBundle:Password:ask' }

WSUserBundle_password_send:
    pattern:   '%ws_user.password_reset.path_send%'
    defaults:  { _controller: 'WSUserBundle:Password:sendEmail' }

WSUserBundle_password_reset:
    pattern:   '%ws_user.password_reset.path_reset%/{token}'
    defaults:  { _controller: 'WSUserBundle:Password:reset' }

WSUserBundle_password_confirm:
    pattern:   '%ws_user.password_reset.path_confirm%'
    defaults:  { _controller: 'WSUserBundle:Password:confirm' }