WSUserBundle_register_register:
    pattern:   '%ws_user.register.path_register%'
    defaults:  { _controller: 'WSUserBundle:Register:register' }

WSUserBundle_register_wait:
    pattern:   '%ws_user.register.path_wait%'
    defaults:  { _controller: 'WSUserBundle:Register:waitCheckEmail' }

WSUserBundle_register_confirm:
    pattern:   '%ws_user.register.path_confirm%'
    defaults:  { _controller: 'WSUserBundle:Register:confirm' }

WSUserBundle_register_check_email:
    pattern:   '%ws_user.register.path_check%/{token}'
    defaults:  { _controller: 'WSUserBundle:Register:checkEmail' }